### ISSUE TITLE
Custom names - Feature

### ISSUE THREAD

**Issue by jsnfjsfjbwiea** [Xenophilicy/FoodEffects#2]
Allow an option to change the item with the effects to make it have a custom name. So I’m doing an Adventure server with many different foods, and I want them to have a custom name when people find them.

**Comment by Xenophilicy** [comment]
This is a little far-fetched but I'll see if I have time to put this in a future update 👍

**Comment by Xenophilicy** [comment]
Added in version 1.2.0, check Poggit for updates [here](https://poggit.pmmp.io/p/FoodEffects)
